### ISSUE TITLE
Diagram attached to wiki not shown after page reload

### ISSUE THREAD

**Issue by df46** [mikitex70/redmine_drawio#48] opened 2017-12-27 21:18 UTC
Dear, 

I've got an issue similar to the #19, in wiki page the edition of draw.io element is not display after a page reload. 

Steps to reproduce

    Go to an wiki
    edit the drawio element
    save in drawio
    all fine so far, diagram is shown
    reload the page

The modification disapear after the page realaod

-----
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  hide_journal_details           0.0.2
  redmine_banner                 0.1.2
  redmine_default_custom_query   1.2.0
  redmine_documents              1.0.0
  redmine_drawio                 0.8.0
  redmine_my_page                0.1.10
  redmine_user_specific_theme    1.2.0
  redmine_wiki_extensions        0.7.0
  sidebar_hide                   0.0.8
  vote_on_issues                 1.0.2

**Comment by mikitex70** [comment] 2017-12-28 15:34
1. did you use the diagrams as attachments or documents?
2. are you using the plugin from the master branch or from the develop branch?
3. do you have non-ASCII character in the wiki page URL?

Try to see in the browser's Javascript console if there is an error: it's strange that there were no popups with error messages.

**Comment by df46** [comment] 2017-12-29 16:32
1. I'm using the diagram as attachment {{drawio_attach(cycle_demandes.png)}}
2. I'm using the master branch but I can try the develop branch
3. Most of time, I try to avoid it (this is the case in my test)

The edition of the diagram, works fine in issue description or journal. I only have the issue in wiki

**Comment by mikitex70** [comment] 2018-01-03 17:29
I've created a dockerized testing environment but I'm unable to reproduce your problem.
My testing environment:

    Environment:
      Redmine version                3.3.2.stable
      Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
      Rails version                  4.2.7.1
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.8.8
      Darcs                          2.8.4
      Mercurial                      2.8.2
      Cvs                            1.12.13
      Bazaar                         2.7.0
      Git                            2.11.0
      Filesystem                      
    Redmine plugins:
      hide_journal_details           0.0.2
      redmine_banner                 0.1.2
      redmine_default_custom_query   1.2.0
      redmine_documents              1.0.0
      redmine_drawio                 0.8.0
      redmine_my_page                0.1.10
      redmine_user_specific_theme    1.2.0
      redmine_wiki_extensions        0.7.0
      sidebar_hide                   0.0.8
      vote_on_issues                 1.0.2

Take a look to the attachments to see if there are multiple versions (I expect multiple versions if you edit the diagram). If there is always only one attachment then there is a problem during save; otherwise maybe that the wiki text is not updated after saving the diagram (wiki page must reflect the generated diagram attachment name).

**Comment by nanego** [comment] 2019-05-15 15:14
Hi @df46
Can you please confirm that this bug is fixed with the last version of the plugin?

**Comment by mikitex70** [comment] 2019-05-19 06:48
Re-tested the plugin versin 0.8.3 with a dockerized Redmine 3.3.2 and it works as expected.
For me the bug is closed.

**Closed by mikitex70** 2019-05-19 06:48 UTC

**Comment by df46** [comment] 2019-05-25 10:28
Sorry for the delay, I"vd tested the 0.8.3 and it's works fine. 

Thanks a lot
