### ISSUE TITLE
Draw.io drawing within Project Description text

### ISSUE THREAD

**Issue by whotopia** [mikitex70/redmine_drawio#113] opened 2022-06-22 22:57 UTC
I'm trying to get a draw.io drawing into Redmine Project Descroption text field.

I  have tried:

1. drawio_attach directly in the description doesn't work. I get message "«Please save content first»"
2. tried to use {{include(Wiki)}} from a wiki page.  That works but the drawio section says "Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'."

Does anyone have any suggestions?  

Lastly, and related,   I was wonderingif you can use the drawio_attach  macro to display a diagram wherein the .xml file is hosted NOT on the same wiki page?  I do not have the dmsf plugin installed.

**Comment by mikitex70** [comment] 2022-06-25 13:27
I @whotopia, the plugin was designed mainly for the wiki page, then updated to work with issues.
Never tested in the project description, I can take a look at it to make it work.
Diagrams are loaded from attachments or with the dmsf plugin, so without the dmsf it's not easy to get something to draw in the project description page. 
I will check if it's possible to load from documents, but then it can be difficult to update it. And it will take me some time so you need to wait...

**Comment by mikitex70** [comment] 2022-06-26 16:14
I've done some test.
The `drawio_attach` macro cannot be used in the project description because it wants to attach the diagram image, and it's not possible with the project description.
But using the `include` macro to include a wiki page works fine, the diagram is shown correctly and no errors arise.
Tested on Redmine `4.2.1` and plugin `1.3.1`.
Can you post the stack trace of the error, if logged by Redmine?

**Comment by mikitex70** [comment] 2023-06-24 14:00
No more feedback, I close the issue.

**Closed by mikitex70** 2023-06-24 14:00 UTC
Labels: enhancement, needs investigation
