### ISSUE TITLE
drawio plugin can't work with CKEditor

### ISSUE THREAD

**Issue by sunnylin13** [mikitex70/redmine_drawio#103] opened 2021-12-01 09:42 UTC
Here is my redmine  information:
Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  redmine_ckeditor               1.2.3
  redmine_dashboard              2.11.0
  redmine_dmsf                   2.4.8
  redmine_drawio                 1.2.0
  redmine_gitlab_hook            4.0.0
  redmine_issue_templates        1.1.0
  redmine_issues_tree            0.0.14
  redmine_lightbox2              0.5.1
  redmine_pivot_table            0.0.7
  redmine_xapian                 2.0.5

In Wiki & Issue editor show blank as below image:
![image](https://user-images.githubusercontent.com/95345180/144210130-63471336-0047-4800-b1da-45e8066e9d1f.png)

In setting editor is workable but still don't have drawio icon:
![image](https://user-images.githubusercontent.com/95345180/144210464-e4812cf7-7a7b-4a64-9280-652552a264c6.png)

**Comment by mikitex70** [comment] 2021-12-01 19:52
Hi @sunnylin13, can you press F12 and check in the console if there is some error? I cannot reproduce the issue.
In wiki and issue pages the drawio buttons are shown correctly; in settings page they aren't show, I'm trying to fix it.

**Comment by sunnylin13** [comment] 2021-12-02 03:08
Hi @mikitex70 , thanks for your information.
After check the console, I found that issued come from incomplete installation of ckeditor plugin, base64image.
And, that come from instruction 'https://www.redmine.org/boards/2/topics/58357' that I try to enable 'Paste an image from the clipboard'. It miss guiding to install 'base64image' plugin. No 'drawio' redmine plugin, even no 'base64image' ckeditor plugin would not cause blank ckeditor issue, but just 'Paste an image from the clipboard' still not work. I just left it behind ... long ago.
Anyway, this issue help me fix both problem. After I install 'base64image' plugin, everything go fine.
Sorry for false issue and thanks your quick response.

**Comment by mikitex70** [comment] 2021-12-02 17:32
I'm glad to know that you have solved it.
Closing this issue, the toolbar buttons in the project settings page is not so important (for now), as diagrams in the project description are rarely used (but macros are still working).

**Closed by mikitex70** 2021-12-02 17:32 UTC
